name: facebook_id_finder
description: A Dart packge to find facebook page, group or profile id..
version: 1.0.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  path: ^1.8.0
  http:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
